name: powers
description: >-
  Extension methods for the num (int and double) class that adds
  functionality for finding the square, cube, and higher order roots
  and powers of the number.
version: 1.0.0
homepage: https://github.com/james-alex/powers

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
