name: powers
description: >-
  Extension for the num (int and double) class that adds
  methods for finding the square, cube, and higher order roots
  and powers of the number.
version: 0.1.0
homepage: https://github.com/james-alex/powers

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.3
